# Generated by Django 4.2.1 on 2023-07-14 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('email', models.CharField(max_length=254, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('isverified', models.IntegerField(db_column='isVerified')),
                ('otp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'base_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'base_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'base_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientid', models.AutoField(db_column='ClientID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=255)),
                ('middlename', models.CharField(blank=True, db_column='MiddleName', max_length=255, null=True)),
                ('lastname', models.CharField(db_column='LastName', max_length=255)),
                ('dateofbirth', models.DateField(db_column='DateOfBirth')),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('depositid', models.AutoField(db_column='depositID', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('clientid', models.IntegerField(db_column='ClientID')),
            ],
            options={
                'db_table': 'deposits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('withdrawalid', models.AutoField(db_column='withdrawalID', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('clientid', models.IntegerField(db_column='ClientID')),
            ],
            options={
                'db_table': 'withdrawals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accountdata',
            fields=[
                ('investor', models.CharField(blank=True, db_column='Investor', max_length=255, null=True)),
                ('clientid', models.OneToOneField(db_column='ClientID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='base.client')),
                ('accountid', models.IntegerField(db_column='AccountID')),
                ('cashbalance', models.IntegerField(db_column='cashBalance')),
                ('totalbalance', models.IntegerField(db_column='totalBalance')),
            ],
            options={
                'db_table': 'accountdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientvariables',
            fields=[
                ('accounttype', models.CharField(blank=True, db_column='accountType', max_length=255, null=True)),
                ('risklevel', models.CharField(blank=True, db_column='riskLevel', max_length=255, null=True)),
                ('investmentgoals', models.CharField(blank=True, db_column='investmentGoals', max_length=255, null=True)),
                ('expectedutility', models.IntegerField(db_column='expectedUtility')),
                ('riskaversion', models.IntegerField(db_column='riskAversion')),
                ('lossaversion', models.IntegerField(db_column='lossAversion')),
                ('reflection', models.IntegerField()),
                ('solrisk', models.IntegerField(db_column='SOLRisk')),
                ('clientid', models.OneToOneField(db_column='ClientID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='base.client')),
            ],
            options={
                'db_table': 'clientvariables',
                'managed': False,
            },
        ),
    ]
