# Generated by Django 4.2.4 on 2023-08-26 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdata',
            name='clientid',
        ),
        migrations.RemoveField(
            model_name='clientvariables',
            name='clientid',
        ),
        migrations.DeleteModel(
            name='Deposits',
        ),
        migrations.DeleteModel(
            name='Withdrawals',
        ),
        migrations.DeleteModel(
            name='Accountdata',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Clientvariables',
        ),
    ]
